### ISSUE TITLE
Unable to compile on ubuntu 16.04

### ISSUE THREAD

**Issue by crackfoo** [wayawolf/WayaWolfCoin#5]
Hi, 

compiling fails in the end with:

/bin/sh ../share/genbuild.sh obj/build.h
g++ -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/src/WayaWolfCoin/src -I/home/src/WayaWolfCoin/src/obj -I/usr/local/BerkeleyDB.4.8/include -DUSE_IPV6=0 -I/home/src/WayaWolfCoin/src/leveldb/include -I/home/src/WayaWolfCoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -o wayawolfcoind leveldb/libleveldb.a obj/alert.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/db.o obj/init.o obj/keystore.o obj/main.o obj/net.o obj/protocol.o obj/bitcoinrpc.o obj/rpcdump.o obj/rpcnet.o obj/rpcmining.o obj/rpcwallet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/script.o obj/scrypt.o obj/sync.o obj/util.o obj/wallet.o obj/walletdb.o obj/hash.o obj/bloom.o obj/noui.o obj/leveldb.o obj/txdb.o -Wl,-z,relro -Wl,-z,now  -L/usr/local/BerkeleyDB.4.8/lib -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -Wl,-Bdynamic -l z -l dl -l pthread /home/src/WayaWolfCoin/src/leveldb/libleveldb.a /home/src/WayaWolfCoin/src/leveldb/libmemenv.a
obj/addrman.o: In function `CAddrMan::Good_(CService const&, long long)':
/tmp/WayaWolfCoin/src/addrman.cpp:307: undefined reference to `CService::ToString() const'
collect2: error: ld returned 1 exit status
makefile.unix:193: recipe for target 'wayawolfcoind' failed
make: *** [wayawolfcoind] Error 1

Any suggestions?
